# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3857056c9d3403850e6853269c0ca16c5a2864f87a713fd56358086b04f49846a59c85ed3ea61c0e49838a564a4829897570d84cbd2b26c19f2358d91716e27a

test:
  secret_key_base: 30908ca97d3a894844c9997f11d431025ecfa123abf44858a3d1831f92853d5c898aa47a7bfb5a603c6403f6b45abd3783ee8422ebe18b677ea804bc863464ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
